# Generated by Django 5.1.6 on 2025-03-17 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_groups', '0002_initial'),
        ('app_lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworkgrade',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_grade', to='app_lessons.homework'),
        ),
        migrations.AddField(
            model_name='homeworkgrade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_homework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups', to='app_groups.groups'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_lesson', to='app_lessons.lesson'),
        ),
    ]
