# Generated by Django 5.1.6 on 2025-03-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
